### ISSUE TITLE
Update to use can-reflect

### ISSUE THREAD

**Issue by matthewp** [canjs/can-connect-ndjson#3]
Not sure if can-reflect is ready yet or not? cc @justinbmeyer @phillipskevin

**Comment by justinbmeyer** [comment]
What does this need to use `can-reflect` for?  It's ready enough to work from, but not quite make a release.

**Comment by matthewp** [comment]
It only works with can-define/list: https://github.com/canjs/can-connect-ndjson/blob/b0fdb882cd634d472b6b5bd195fbd3ffda19104f/can-connect-ndjson.js#L38
